// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy53bAbsyLPGRnIVctdD9UQ6Aene4Uj0k',
    appId: '1:1059808316:web:b889c140f567ebd62a0f39',
    messagingSenderId: '1059808316',
    projectId: 'finalprojectdavid',
    authDomain: 'finalprojectdavid.firebaseapp.com',
    storageBucket: 'finalprojectdavid.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJLy_YrJV_3kuiKFRjDhDHWE61CrDNN-Q',
    appId: '1:1059808316:android:a5cd0bb55c68dc3f2a0f39',
    messagingSenderId: '1059808316',
    projectId: 'finalprojectdavid',
    storageBucket: 'finalprojectdavid.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJyd2SlgQfEvXlvi31DWS7E--nzYTMAas',
    appId: '1:1059808316:ios:006a7535ba078bfb2a0f39',
    messagingSenderId: '1059808316',
    projectId: 'finalprojectdavid',
    storageBucket: 'finalprojectdavid.appspot.com',
    iosClientId: '1059808316-jkogj02glfs4ko5191vq58h7h9jmlbn6.apps.googleusercontent.com',
    iosBundleId: 'com.example.davidFinalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJyd2SlgQfEvXlvi31DWS7E--nzYTMAas',
    appId: '1:1059808316:ios:006a7535ba078bfb2a0f39',
    messagingSenderId: '1059808316',
    projectId: 'finalprojectdavid',
    storageBucket: 'finalprojectdavid.appspot.com',
    iosClientId: '1059808316-jkogj02glfs4ko5191vq58h7h9jmlbn6.apps.googleusercontent.com',
    iosBundleId: 'com.example.davidFinalProject',
  );
}
